name: Flight Price Check

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  check-flights:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install
      
      - name: Check flight prices
        env:
          AMADEUS_API_KEY: ${{ secrets.AMADEUS_API_KEY }}
          AMADEUS_API_SECRET: ${{ secrets.AMADEUS_API_SECRET }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: npm run check
      
      - name: Commit price history
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add price-history.json || true
          git commit -m "Update price history" || true
          git push || true
      
      - name: Job complete
        run: echo "Flight check completed at $(date)"